//! Build-time guards over the hand-written stylesheets and the iOS plist.
//!
//! These files carry invariants that nothing else enforces: a material without its
//! reduced-transparency fallback, a `:hover` that latches on touch, a plist key pointing at a
//! resource that does not exist. All three have shipped. They are checked here, in `ui`, because
//! `ui` is the crate whose components render `.card-clickable` and `.chrome-material` and depends
//! on all three shells defining them — the shared contract belongs with the consumer — and because
//! `cargo test --package ui` is the one a CI job actually runs.
//!
//! Modelled on the `ftl` guards in `i18n.rs`, which read the locale files and the crate source off
//! disk for the same reason. Like those, every read is `.expect(…)`: a guard that passes because it
//! found no file is the failure mode to design against.

use std::collections::BTreeSet;
use std::path::PathBuf;

/// The three hand-written stylesheets. `assets/tailwind.css` beside each is generated by
/// `npm run build:css` and already guarded by the `check-css` CI job; these are not.
const STYLESHEETS: [&str; 3] = [
    "../mobile/assets/main.css",
    "../web/assets/main.css",
    "../desktop/assets/main.css",
];

fn read(rel: &str) -> String {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(rel);
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("guard cannot read {}: {e}", path.display()))
}

/// `/* … */` removed. Without this every assertion below trips on its own explanatory comment —
/// the reduced-transparency block's comment names `backdrop-filter`, and the card rule's names
/// `:hover`.
fn strip_comments(css: &str) -> String {
    let mut out = String::with_capacity(css.len());
    let bytes = css.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'/' && bytes.get(i + 1) == Some(&b'*') {
            match css[i + 2..].find("*/") {
                Some(end) => i += 2 + end + 2,
                None => break,
            }
            // Keep a separator so `a/*x*/{` cannot fuse into a different token.
            out.push(' ');
        } else {
            out.push(bytes[i] as char);
            i += 1;
        }
    }
    out
}

/// One CSS declaration, with the block preludes enclosing it (outermost first).
struct Decl {
    prop: String,
    value: String,
    stack: Vec<String>,
}

impl Decl {
    /// The innermost prelude that is a selector rather than an at-rule.
    fn selector(&self) -> Option<&str> {
        self.stack.iter().rev().find(|p| !p.starts_with('@')).map(|s| s.as_str())
    }

    fn under_at_rule(&self, needle: &str) -> bool {
        self.stack.iter().any(|p| p.starts_with('@') && normalize(p).contains(needle))
    }
}

/// Whitespace collapsed, so `hover:  hover` and `hover: hover` compare equal.
fn normalize(s: &str) -> String {
    s.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// A brace-aware walk. Enough for these files — they are hand-written, comment-stripped, and
/// contain no strings or url() with unbalanced braces.
fn declarations(css: &str) -> Vec<Decl> {
    let mut out = Vec::new();
    let mut stack: Vec<String> = Vec::new();
    let mut cur = String::new();
    for c in css.chars() {
        match c {
            '{' => {
                stack.push(normalize(&cur));
                cur.clear();
            }
            '}' => {
                stack.pop();
                cur.clear();
            }
            ';' => {
                if let Some((prop, value)) = cur.split_once(':') {
                    out.push(Decl {
                        prop: normalize(prop),
                        value: normalize(value),
                        stack: stack.clone(),
                    });
                }
                cur.clear();
            }
            _ => cur.push(c),
        }
    }
    out
}

/// Every selector in a comma-separated prelude, normalized.
fn selector_parts(prelude: &str) -> impl Iterator<Item = String> + '_ {
    prelude.split(',').map(normalize).filter(|s| !s.is_empty())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Fix 1's guard. A translucent bar that ignores Reduce Transparency is an accessibility
    /// regression that looks perfectly fine to whoever added it — which is exactly how it shipped
    /// the first time.
    #[test]
    fn every_backdrop_filter_has_a_reduced_transparency_fallback() {
        for file in STYLESHEETS {
            let css = strip_comments(&read(file));
            let decls = declarations(&css);

            let mut blurred = BTreeSet::new();
            let mut covered = BTreeSet::new();
            for d in &decls {
                if !d.prop.ends_with("backdrop-filter") {
                    continue;
                }
                let Some(sel) = d.selector() else { continue };
                if d.under_at_rule("prefers-reduced-transparency") {
                    covered.extend(selector_parts(sel));
                } else if d.value != "none" {
                    blurred.extend(selector_parts(sel));
                }
            }

            let missing: Vec<_> = blurred.difference(&covered).cloned().collect();
            assert!(
                missing.is_empty(),
                "{file}: these set backdrop-filter with no \
                 @media (prefers-reduced-transparency: reduce) fallback: {missing:?}"
            );
        }
    }

    /// Fix 3's guard. iOS latches `:hover` on tap and holds it until the next tap elsewhere, so an
    /// unwrapped hover leaves a card highlighted behind the page it opened. Tailwind already wraps
    /// its own `hover:` utilities; this catches the hand-written ones.
    #[test]
    fn no_hover_rule_applies_to_touch() {
        for file in STYLESHEETS {
            let css = strip_comments(&read(file));
            let offenders: Vec<String> = declarations(&css)
                .iter()
                .filter_map(|d| {
                    let sel = d.selector()?;
                    let hovers = selector_parts(sel).any(|s| s.contains(":hover"));
                    (hovers && !d.under_at_rule("hover: hover")).then(|| sel.to_string())
                })
                .collect();
            assert!(
                offenders.is_empty(),
                "{file}: :hover outside @media (hover: hover) — it will latch on touch: {offenders:?}"
            );
        }
    }

    /// Every variable the JS hooks write must have a `:root` default, or the rules consuming it are
    /// invalid for the whole window between first paint and the effect landing.
    #[test]
    fn every_runtime_css_variable_has_a_root_default() {
        let css = strip_comments(&read(STYLESHEETS[0]));
        let rooted: BTreeSet<String> = declarations(&css)
            .iter()
            .filter(|d| d.selector().is_some_and(|s| s == ":root") && d.prop.starts_with("--"))
            .map(|d| d.prop.clone())
            .collect();
        for var in ["--sat", "--sab", "--sar", "--dt-scale", "--kb", "--overscroll", "--ptr-pull"] {
            assert!(rooted.contains(var), "{var} has no :root default in {}", STYLESHEETS[0]);
        }
    }
}
