use dioxus::prelude::*;

#[derive(Clone, PartialEq)]
pub enum Licenses {
    Loading,
    Failed,
    Loaded(String),
}

/// `packages/ui/licenses/third-party.txt`, generated by `make licenses`: ~420 KB, so the web build
/// fetches it as a hashed asset instead of carrying it in the wasm. Loaded in an effect, never
/// during SSR, so the server markup and the first client render agree.
pub fn use_third_party_licenses() -> Signal<Licenses> {
    let mut licenses = use_signal(|| Licenses::Loading);
    use_effect(move || {
        spawn(async move {
            licenses.set(match load().await {
                Some(text) => Licenses::Loaded(text),
                None => Licenses::Failed,
            });
        });
    });
    licenses
}

#[cfg(target_arch = "wasm32")]
async fn load() -> Option<String> {
    crate::common::web_dom::fetch_text(&asset!("/licenses/third-party.txt").to_string()).await
}

#[cfg(any(target_os = "android", target_os = "ios"))]
async fn load() -> Option<String> {
    Some(include_str!("../../licenses/third-party.txt").to_string())
}

#[cfg(not(any(target_arch = "wasm32", target_os = "android", target_os = "ios")))]
async fn load() -> Option<String> {
    None
}
